# Generated by Django 5.1 on 2025-11-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_emp', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('puesto', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=15)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('id_atr', models.IntegerField()),
            ],
        ),
    ]
